import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ToastProvider from "@/provider/toast-provider";
import { ModelProvider } from "@/provider/model-provider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Admin E-Commerece dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToastProvider />
          <ModelProvider />
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
